// Gegenereerd uit docs/pleya-protocol/v1/openapi.yaml. Niet met de hand wijzigen.
// Opnieuw genereren: pleya_web/scripts/gen-api-types.sh
// bron-sha256: 2e679d946667abeec0e93550b6ca903f28217b381add62c33c0c61a15731a901
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wat staat er aan de andere kant.
         * @description Klasse `public`. Bereikbaar zonder authenticatie, want een client moet
         *     weten wat er staat voordat hij een inlogpoging doet. Draagt daarom
         *     bewust geen servernaam, versie of buildnummer; die staan in /server.
         */
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Maak de bootstrap-eigenaar aan met de setupcode.
         * @description Klasse `public`, en uitsluitend zolang info.auth.setup_required waar is.
         *     De eerste start van een server drukt een eenmalige code af op de console.
         */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wissel gebruikersnaam en wachtwoord in voor een tokenpaar. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ververs het tokenpaar.
         * @description Klasse `public`, want het refreshtoken is zelf het bewijs. Het token
         *     roteert bij elk gebruik en het oude vervalt onmiddellijk. Een tweede
         *     aanroep met hetzelfde token geeft auth.refresh_token_reused, en de
         *     server mag de hele keten dan ongeldig maken.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/stream-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vraag een kortlevend token voor bytes.
         * @description Klasse `authenticated`. Voor spelers die geen header kunnen zetten.
         *     Kortlevend en smal, maar NIET eenmalig: een speler doet een HEAD, dan
         *     een open range, dan losse ranges per seek, plus retries. Een token dat
         *     na de eerste range vervalt breekt op de tweede.
         */
        post: operations["issueStreamToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/stream-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open een browser-streamsessie.
         * @description Klasse `authenticated`. Alleen aanwezig wanneer `capabilities.stream_sessions`
         *     waar is; een client vraagt er niet om zonder die vlag.
         *
         *     Waarvoor. Een `<video>`-element stuurt bij elke seek een nieuwe
         *     range-aanvraag met de URL uit `src`, en het streamtoken uit
         *     /auth/stream-token leeft twee tot vijf minuten. Een lange film breekt
         *     daardoor op de eerste seek na die tijd. Een streamsessie leeft langer en
         *     houdt het geheim buiten de URL.
         *
         *     Hoe. Het antwoord draagt een niet-geheime `stream_session_id`, en de
         *     server zet daarnaast een cookie waarvan de NAAM die id bevat:
         *     `pleya_ss_<stream_session_id>=<geheim>; HttpOnly; SameSite=Strict;
         *     Path=/pleya/v1/stream/`, met `Secure` waar de context dat toelaat. Een
         *     cookienaam per sessie, want cookies met dezelfde naam, domein en pad
         *     vervangen elkaar en twee gelijktijdige streams zouden elkaar dan breken.
         *     De client zet de id in de media-URL als `ss`; het geheim komt nooit in
         *     een URL, een log of een referrer.
         *
         *     Grens. Ten hoogste acht ACTIEVE sessies per subject. De server ruimt
         *     eerst verlopen en ingetrokken sessies op; blijven er acht over, dan
         *     weigert hij de negende met `session.stream_session_limit`. Een nog
         *     levende stream wordt niet stilzwijgend beëindigd om plaats te maken.
         *
         *     Op een LAN zonder TLS reist het geheim in klare tekst. `HttpOnly` houdt
         *     JavaScript op de pagina eruit; het is geen versleuteling.
         */
        post: operations["createStreamSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serverdetail achter authenticatie. */
        get: operations["getServer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alle zichtbare bibliotheken.
         * @description Niet gepagineerd; een huishouden heeft er een handvol.
         */
        get: operations["listLibraries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{library_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blader door een bibliotheek.
         * @description Een bibliotheek van soort `shows` levert uitsluitend items met
         *     kind `show`. Seizoenen en afleveringen bereikt u via /items/{id}/children.
         */
        get: operations["listLibraryItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eén item met zijn versies en kijkstatus. */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seizoenen van een serie, afleveringen van een seizoen.
         * @description Voor een film is het antwoord een lege lijst en geen fout.
         */
        get: operations["listItemChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zoek over alle bibliotheken.
         * @description Resultaten zijn gewone itemobjecten. Er is geen apart resultaattype en
         *     geen groepering per soort; de client groepeert zelf en hoeft daarvoor
         *     geen tweede vorm te kennen.
         *
         *     Zonder kind levert een zoekopdracht items van soort movie, show en
         *     episode. Seizoenen blijven eruit: hun titel is "Season 3" en draagt
         *     niets van wat een gebruiker intypt, dus ze voegen alleen ruis toe aan
         *     korte zoektermen. Een seizoen is met kind=season wel op te vragen en
         *     staat verder in de kinderen van zijn serie.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs/{hub_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bouwstenen voor het homescherm.
         * @description De server levert bouwstenen en geen schermindeling; de client bouwt zijn
         *     eigen rijen. Een server zonder kijkstatus levert lege lijsten voor
         *     continue_watching en next_up, en geen fout.
         */
        get: operations["getHub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artwork/{artwork_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Een afbeelding, eventueel op maat.
         * @description Artwork is onveranderlijk: een andere afbeelding krijgt een ander id.
         *     In v1 levert de server uitsluitend afbeeldingen die naast de media op
         *     schijf staan; een 404 is daarom een normale toestand en geen storing.
         */
        get: operations["getArtwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subtitles/{subtitle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Een ondertitelbestand. */
        get: operations["getSubtitle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Direct play met HTTP-range.
         * @description Het hoofdpad en verreweg het meeste verkeer. Geen sessie, geen state,
         *     geen opruimwerk.
         *
         *     Eén bereik per aanvraag. Een Range-header met meerdere bereiken wordt
         *     beantwoord met het volledige bestand als 200; dat is de toegestane
         *     terugval en houdt een speler die het toch probeert aan de praat, waar
         *     een 416 hem zou breken.
         *
         *     De ETag is een ZWAKKE validator (`W/"..."`). Pleya beheert de bestanden
         *     niet: ze staan op mounts die er buiten Pleya om vervangen worden, en RFC
         *     9110 §8.8.1 vraagt van een sterke validator strict revision control of
         *     een collision-resistant hash over de bytes. Geen van beide is er, dus de
         *     belofte staat er niet.
         *
         *     Gevolg voor If-Range: de server negeert de Range-header en antwoordt met
         *     de volledige representatie als 200, de terugval uit RFC 9110 §13.1.5.
         *     Een conformante client stuurt If-Range sowieso niet met een zwakke
         *     validator.
         *
         *     Een VERSCHILLENDE ETag betekent: er is iets veranderd, gooi de buffer
         *     weg. Een GELIJKE ETag zegt niets over de bytes en is nooit grond om twee
         *     los opgehaalde bereiken aan elkaar te plakken. Hervatten na een
         *     onderbreking gaat met een gewone Range-aanvraag.
         */
        get: operations["getStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alles wat deze identiteit heeft aangeraakt.
         * @description Gesorteerd op updated_at aflopend. updated_since is wat de offline-laag
         *     gebruikt om na een periode zonder netwerk bij te trekken zonder de hele
         *     catalogus op te halen.
         */
        get: operations["listWatchState"];
        put?: never;
        /**
         * Meld wat er gebeurd is.
         * @description Een update is een gebeurtenis en geen waarde. De client stuurt niet "de
         *     positie is nu X" maar "dit is er gebeurd", en de server beslist wat dat
         *     voor de toestand betekent.
         *
         *     session_id is client-generated: de client maakt bij het starten van
         *     afspelen een UUID aan en houdt die aan tot hij stopt. Er zijn in v1
         *     bewust geen serverzijdige playbacksessies, dus er is ook geen endpoint
         *     dat een sessie-id uitdeelt.
         *
         *     Op een server met capabilities.watch_state_ownership beslist het model
         *     uit DEC-049 wat een event met de toestand doet. De server is eigenaar:
         *     alleen de sessie met een geldige lease schrijft de canonieke positie,
         *     eigendom wordt uitsluitend verworven met explicit_action =
         *     playback_started, en base_revision draagt de causaliteit.
         *
         *     Het antwoord is ALTIJD de actuele toestand, ook wanneer het event is
         *     afgewezen. Een client die een 200 krijgt met een hogere revision dan hij
         *     stuurde weet daarmee dat hij achterliep, en synchroniseert in plaats van
         *     door te schrijven. Er is dus geen foutcode voor "u bent niet de
         *     eigenaar"; dat is een normale uitkomst en geen fout.
         */
        post: operations["reportWatchState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Ondoorzichtig voor de client. Er mag niets uit worden afgeleid, ook niet
         *     wanneer het op iets herkenbaars lijkt. Een pad is nooit een id.
         */
        Id: string;
        /**
         * Format: date-time
         * @description RFC 3339 in UTC, met Z-achtervoegsel.
         */
        Timestamp: string;
        /** @description Milliseconden. Nooit seconden, nooit een kommagetal. */
        DurationMs: number;
        ErrorEnvelope: {
            error: {
                /** @description Het contract. De client vertaalt codes en matcht nooit op message. */
                code: string;
                /** @description Voor logs, niet voor de UI. */
                message: string;
                /**
                 * @description Expliciet en geen afleiding uit de status, omdat een 503 soms wel
                 *     en een 409 soms niet te herhalen is.
                 */
                retryable: boolean;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Info: {
            protocol: {
                /** @constant */
                major: 1;
                /**
                 * @description Wat de implementatie kan verstaan. Zegt niets over wat deze
                 *     server aanbiedt; daarvoor is capabilities leidend.
                 */
                feature_level: number;
                /** @enum {string} */
                profile: "minimal" | "full";
            };
            server: {
                id: components["schemas"]["Id"];
            };
            capabilities: components["schemas"]["Capabilities"];
            auth: {
                methods: ("password" | "pairing_code")[];
                /** @description True zolang er nog geen eigenaar is aangemaakt. */
                setup_required: boolean;
            };
        };
        /** @description Altijd leidend boven feature_level. */
        Capabilities: {
            browse: boolean;
            search: boolean;
            artwork: boolean;
            watch_state: boolean;
            /** @default false */
            playback_plan: boolean;
            /** @default false */
            transcode: boolean;
            /** @default false */
            downloads: boolean;
            /** @default false */
            live_tv: boolean;
            /** @default false */
            realtime: boolean;
            /** @default false */
            users: boolean;
            /**
             * @description De server kent het eigendomsmodel uit DEC-049: base_revision, de
             *     playback_started-verwerving en de backlog-markering op
             *     WatchStateEvent, en revision op UserState. WatchStateEvent is
             *     gesloten (additionalProperties: false), dus een client stuurt die
             *     velden pas wanneer deze vlag waar is.
             * @default false
             */
            watch_state_ownership: boolean;
            /**
             * @description De server kent POST /auth/stream-session en de ss-parameter op
             *     /stream. Voor browsers; externe spelers blijven het streamtoken in
             *     de querystring gebruiken.
             * @default false
             */
            stream_sessions: boolean;
        };
        ServerDetail: {
            id: components["schemas"]["Id"];
            name: string;
            version: string;
            started_at: components["schemas"]["Timestamp"];
        };
        SetupRequest: {
            setup_code: string;
            username: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            /** @description Roteert bij elk gebruik; het oude vervalt onmiddellijk. */
            refresh_token: string;
            /** @constant */
            token_type: "bearer";
            expires_in_ms: components["schemas"]["DurationMs"];
        };
        StreamTokenRequest: {
            version_id: components["schemas"]["Id"];
        };
        StreamSessionRequest: {
            version_id: components["schemas"]["Id"];
        };
        StreamSession: {
            /**
             * @description Niet geheim. Hoort in de ss-parameter van de media-URL. Het geheim
             *     zit in de cookie met de naam `pleya_ss_<stream_session_id>` en komt
             *     nergens anders voor.
             */
            stream_session_id: string;
            expires_at: components["schemas"]["Timestamp"];
        };
        StreamToken: {
            stream_token: string;
            expires_at: components["schemas"]["Timestamp"];
        };
        /**
         * @description Er mag binnen v1 een soort bij komen. Een client die de soort niet kent
         *     toont de bibliotheek niet, en faalt niet.
         * @enum {string}
         */
        LibraryKind: "movies" | "shows";
        Library: {
            id: components["schemas"]["Id"];
            title: string;
            kind: components["schemas"]["LibraryKind"];
            item_count: number;
        };
        LibraryList: {
            items: components["schemas"]["Library"][];
        };
        /**
         * @description Er mag binnen v1 een soort bij komen. Een client die de soort niet kent
         *     toont het item niet, en faalt niet.
         * @enum {string}
         */
        ItemKind: "movie" | "show" | "season" | "episode";
        /** @description Ids van beschikbare afbeeldingen. Null wanneer er geen is. */
        Artwork: {
            poster_id?: components["schemas"]["Id"] | null;
            backdrop_id?: components["schemas"]["Id"] | null;
        };
        VideoStream: {
            id: components["schemas"]["Id"];
            index: number;
            codec: string;
            profile?: string | null;
            width?: number | null;
            height?: number | null;
            bit_depth?: number | null;
            frame_rate?: number | null;
        };
        AudioStream: {
            id: components["schemas"]["Id"];
            index: number;
            codec: string;
            channels?: number | null;
            /** @description ISO 639-2/B in drie letters, of null. */
            language?: string | null;
            title?: string | null;
            /** @default false */
            is_default: boolean;
        };
        /**
         * @description Twee soorten met hetzelfde veldenpakket. Extern heeft een url en geen
         *     index; ingebed heeft een index en geen url.
         */
        SubtitleStream: {
            id: components["schemas"]["Id"];
            /** @description Alleen bij ingebedde sporen. */
            index?: number | null;
            /**
             * @description Er mag binnen v1 een formaat bij komen. Een client die het formaat
             *     niet kent biedt het spoor niet aan, en faalt niet.
             * @enum {string}
             */
            format: "srt" | "ass" | "ssa" | "vtt" | "pgs" | "dvdsub";
            language?: string | null;
            title?: string | null;
            /** @default false */
            is_default: boolean;
            /** @description Expliciet, geen afleiding uit de titel. */
            is_forced: boolean;
            /** @description Expliciet, geen afleiding uit de titel. */
            is_hearing_impaired: boolean;
            is_external: boolean;
            /** @description Alleen bij externe sporen. */
            url?: string | null;
        };
        Version: {
            id: components["schemas"]["Id"];
            container: string;
            duration_ms: components["schemas"]["DurationMs"];
            /**
             * @description Een versie mag uit meerdere bestanden bestaan; dat is geldig in het
             *     domeinmodel. Direct play accepteert in v1 uitsluitend 1.
             */
            file_count: number;
            /** @description Bijvoorbeeld "Director's Cut". Onderscheidt twee snedes van dezelfde titel. */
            edition?: string | null;
            video_streams?: components["schemas"]["VideoStream"][];
            audio_streams?: components["schemas"]["AudioStream"][];
            subtitle_streams?: components["schemas"]["SubtitleStream"][];
        };
        /**
         * @description De leeskant van kijkstatus. Reist mee in elk itemantwoord, zodat een
         *     detailscherm geen tweede aanvraag nodig heeft.
         */
        UserState: {
            position_ms: components["schemas"]["DurationMs"];
            watched: boolean;
            play_count: number;
            updated_at: components["schemas"]["Timestamp"];
            /**
             * @description Monotoon en uitsluitend serverzijdig toegekend. Een client bewaart
             *     de laatst geziene waarde en stuurt hem terug als base_revision, en
             *     de server accepteert een schrijving alleen wanneer die gelijk is aan
             *     de actuele revision. Zo kan een client die op een verouderd beeld
             *     handelde de nieuwere toestand niet overschrijven.
             *
             *     Afwezig op een server zonder capabilities.watch_state_ownership. Een
             *     client die het veld niet kent blijft correct: hij stuurt dan geen
             *     base_revision en de server valt terug op de eigenaarsregel.
             */
            revision?: number;
            /**
             * @description Of de sessie die dit antwoord kreeg op dit moment de canonieke
             *     positie mag schrijven. Alleen aanwezig in het antwoord op
             *     POST /watch-state, en alleen op een server met
             *     capabilities.watch_state_ownership.
             */
            owned_by_this_session?: boolean;
        };
        Item: {
            id: components["schemas"]["Id"];
            kind: components["schemas"]["ItemKind"];
            title: string;
            sort_title?: string | null;
            year?: number | null;
            added_at: components["schemas"]["Timestamp"];
            duration_ms?: components["schemas"]["DurationMs"] | null;
            parent_id?: components["schemas"]["Id"] | null;
            /** @description Seizoen- of afleveringsnummer. */
            index?: number | null;
            child_count?: number | null;
            /** @description Backend-neutrale naam; het interne model van de client heet anders. */
            episode_count?: number | null;
            watched_episode_count?: number | null;
            artwork?: components["schemas"]["Artwork"];
            versions?: components["schemas"]["Version"][];
            user_state?: components["schemas"]["UserState"] | null;
        };
        Page: {
            /** @description Null op de laatste pagina. */
            next_cursor: string | null;
            /**
             * @description Expliciet een schatting, zodat een UI een scrollbar kan tekenen
             *     zonder dat de server per pagina telt. Nooit als exact aantal tonen.
             */
            total_estimate?: number | null;
        };
        ItemPage: components["schemas"]["Page"] & {
            items: components["schemas"]["Item"][];
        };
        /**
         * @description Een expliciete handeling wint van elke passieve update die ervoor ligt.
         *     Dat onderscheid is de reden dat een update een gebeurtenis is.
         *
         *     `playback_started` is de enige manier om het eigendom van de kijkstatus
         *     te verwerven (DEC-049). Een passief voortgangsevent verwerft nooit, ook
         *     niet wanneer de lease van de eigenaar verlopen is. De waarde is alleen
         *     toegestaan wanneer capabilities.watch_state_ownership waar is; het veld
         *     is niet unknown-safe, dus een oudere server wijst hem af in plaats van
         *     hem te negeren.
         *
         *     `mark_watched`, `mark_unwatched` en `restart` negeren de lease van de
         *     huidige eigenaar en nemen het eigendom over. Ze ordenen op
         *     serverontvangst, niet op occurred_at.
         * @enum {string}
         */
        ExplicitAction: "none" | "mark_watched" | "mark_unwatched" | "restart" | "playback_started";
        /**
         * @description Waarom een playback_started binnenkomt. Bij `user_started` heeft iemand
         *     op afspelen gedrukt en neemt die sessie het eigendom over, ongeacht de
         *     lease van een ander. Bij `reclaim` heropent een sessie die zelf nog
         *     speelt haar eigendom, en dat wordt alleen toegekend wanneer de lease van
         *     de huidige eigenaar verlopen is.
         * @enum {string}
         */
        PlaybackCause: "user_started" | "reclaim";
        WatchStateEvent: {
            item_id: components["schemas"]["Id"];
            /**
             * @description Client-generated. De client maakt bij het starten van afspelen een
             *     UUID aan en houdt die aan tot hij stopt.
             */
            session_id: string;
            position_ms: components["schemas"]["DurationMs"];
            duration_ms?: components["schemas"]["DurationMs"] | null;
            /**
             * @description Het moment volgens de client. De server bewaart daarnaast zijn eigen
             *     ontvangstmoment, want een toestel met een scheve klok mag de
             *     volgorde niet bepalen.
             */
            occurred_at: components["schemas"]["Timestamp"];
            /** @default false */
            completed: boolean;
            explicit_action: components["schemas"]["ExplicitAction"];
            /**
             * @description De revision waarop de client zijn beeld baseerde. De server
             *     accepteert de schrijving alleen bij gelijkheid met de actuele
             *     revision; wijkt hij af, dan antwoordt de server met de actuele
             *     toestand en verandert er niets aan de canonieke positie.
             *
             *     Weglaten mag: dan doet het event geen causale claim, en wordt het
             *     alleen geaccepteerd van de huidige eigenaar met een geldige lease.
             *     Een expliciete handeling wordt wél toegepast met een verouderde
             *     base_revision, zolang hij live binnenkomt en niet als backlog.
             *
             *     Alleen te sturen wanneer capabilities.watch_state_ownership waar is.
             */
            base_revision?: number;
            /**
             * @description Verplicht bij explicit_action = playback_started en zinloos
             *     daarbuiten. Alleen te sturen wanneer
             *     capabilities.watch_state_ownership waar is.
             */
            cause?: components["schemas"]["PlaybackCause"];
            /**
             * @description Dit event komt uit een offline wachtrij en niet uit een sessie die nu
             *     speelt. Een backlog verwerft nooit eigendom en verplaatst de
             *     canonieke toestand niet zolang revision > 0, ook niet wanneer de
             *     lease van de eigenaar verlopen is. Alleen bij revision = 0 is er
             *     niets te beschermen en vestigt het laatste event uit de batch de
             *     toestand alsnog.
             *
             *     Alleen te sturen wanneer capabilities.watch_state_ownership waar is.
             * @default false
             */
            backlog: boolean;
        };
        WatchStateEntry: {
            item_id: components["schemas"]["Id"];
            state: components["schemas"]["UserState"];
        };
        WatchStatePage: components["schemas"]["Page"] & {
            items: components["schemas"]["WatchStateEntry"][];
        };
    };
    responses: {
        /** @description Fout met een stabiele machineleesbare code. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        LibraryId: components["schemas"]["Id"];
        ItemId: components["schemas"]["Id"];
        /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
        Limit: number;
        /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
        Cursor: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Zwakke validator, in de vorm `W/"..."`. Ondoorzichtig: een client
         *     ontleedt hem niet en leidt er niets uit af.
         *
         *     Verschillend betekent "er is iets veranderd". Gelijk betekent NIET dat
         *     de bytes gelijk zijn: de server leidt hem af uit bestandsmetadata plus
         *     de generatie van de versie, en een in-place overschrijving van gelijke
         *     lengte met teruggezette mtime blijft daar onder de radar. Gebruik hem
         *     als change detector en nooit als bewijs van byte-identiteit.
         */
        ETag: string;
        AcceptRanges: "bytes";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serverinformatie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"];
                };
            };
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Eigenaar aangemaakt, tokenpaar uitgegeven. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Tokenpaar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /**
             * @description auth.invalid_credentials. Een onbekende gebruiker en een verkeerd
             *     wachtwoord geven hetzelfde antwoord, zodat het bestaan van een
             *     account niet lekt.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Nieuw tokenpaar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    issueStreamToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamTokenRequest"];
            };
        };
        responses: {
            /** @description Streamtoken. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamToken"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    createStreamSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamSessionRequest"];
            };
        };
        responses: {
            /** @description De sessie, plus de cookie in Set-Cookie. */
            200: {
                headers: {
                    /**
                     * @description `pleya_ss_<stream_session_id>=<geheim>`, HttpOnly en
                     *     SameSite=Strict, op Path=/pleya/v1/stream/.
                     */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamSession"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /**
             * @description session.stream_session_limit. Er staan al acht actieve streamsessies
             *     voor dit subject. Beëindig er een of wacht tot er een vervalt.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Naam, versie en starttijd. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerDetail"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bibliotheken. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryList"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listLibraryItems: {
        parameters: {
            query?: {
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Een voorafgaand minteken keert de volgorde om. */
                sort?: "title" | "added_at" | "year" | "-title" | "-added_at" | "-year";
            };
            header?: never;
            path: {
                library_id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Het item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listItemChildren: {
        parameters: {
            query?: {
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                kind?: components["schemas"]["ItemKind"];
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina items. Geen treffers is een lege lijst, geen fout. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getHub: {
        parameters: {
            query?: {
                library_id?: components["schemas"]["Id"];
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                hub_id: "recently_added" | "continue_watching" | "next_up";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getArtwork: {
        parameters: {
            query?: {
                /** @description Zonder deze parameter krijgt u het origineel. */
                width?: number;
            };
            header?: never;
            path: {
                artwork_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description De afbeelding. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    /** @description Lang, want artwork is onveranderlijk. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            /** @description Niet gewijzigd. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getSubtitle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subtitle_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Het ondertitelbestand. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-subrip": string;
                    "text/x-ssa": string;
                    "text/vtt": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getStream: {
        parameters: {
            query?: {
                /**
                 * @description De niet-geheime id van een browser-streamsessie uit
                 *     POST /auth/stream-session. Het bijbehorende geheim reist als cookie
                 *     en staat nooit in de URL. Alleen te gebruiken wanneer
                 *     `capabilities.stream_sessions` waar is.
                 */
                ss?: string;
            };
            header?: {
                /** @example bytes=0-1048575 */
                Range?: string;
                /**
                 * @description De eerder ontvangen ETag. Die is zwak, dus de server kan er geen
                 *     deelantwoord op geven en antwoordt met 200 en het volledige bestand.
                 */
                "If-Range"?: string;
            };
            path: {
                version_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Het hele bestand. Ook het antwoord op meerdere bereiken. */
            200: {
                headers: {
                    "Accept-Ranges": components["headers"]["AcceptRanges"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Het gevraagde bereik. */
            206: {
                headers: {
                    "Accept-Ranges": components["headers"]["AcceptRanges"];
                    ETag: components["headers"]["ETag"];
                    /** @example bytes 0-1048575/5368709120 */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /**
             * @description library.version_multifile. De versie bestaat uit meer dan een
             *     bestand. Dat is een geldige versie in het domeinmodel; v1 begrenst
             *     alleen de levering.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            415: components["responses"]["Error"];
            /** @description playback.range_not_satisfiable. */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    listWatchState: {
        parameters: {
            query?: {
                updated_since?: string;
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina kijkstatusregels. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchStatePage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    reportWatchState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchStateEvent"];
            };
        };
        responses: {
            /** @description De nieuwe toestand van het item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserState"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
