// Gegenereerd uit docs/pleya-protocol/v1/openapi.yaml. Niet met de hand wijzigen.
// Opnieuw genereren: pleya_web/scripts/gen-api-types.sh
// bron-sha256: 309974e92351f6fbd0f50637a27e28dad4ae6cb1d3c7efe7065e6618bfcff2ed
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wat staat er aan de andere kant.
         * @description Klasse `public`. Bereikbaar zonder authenticatie, want een client moet
         *     weten wat er staat voordat hij een inlogpoging doet. Draagt daarom
         *     bewust geen servernaam, versie of buildnummer; die staan in /server.
         */
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Maak de bootstrap-eigenaar aan met de setupcode.
         * @description Klasse `public`, en uitsluitend zolang info.auth.setup_required waar is.
         *     De eerste start van een server drukt een eenmalige code af op de console.
         */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wissel gebruikersnaam en wachtwoord in voor een tokenpaar. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ververs het tokenpaar.
         * @description Klasse `public`, want het refreshtoken is zelf het bewijs. Het token
         *     roteert bij elk gebruik en het oude vervalt onmiddellijk. Een tweede
         *     aanroep met hetzelfde token geeft auth.refresh_token_reused, en de
         *     server mag de hele keten dan ongeldig maken.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/stream-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vraag een kortlevend token voor bytes.
         * @description Klasse `authenticated`. Voor spelers die geen header kunnen zetten.
         *     Kortlevend en smal, maar NIET eenmalig: een speler doet een HEAD, dan
         *     een open range, dan losse ranges per seek, plus retries. Een token dat
         *     na de eerste range vervalt breekt op de tweede.
         */
        post: operations["issueStreamToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serverdetail achter authenticatie. */
        get: operations["getServer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alle zichtbare bibliotheken.
         * @description Niet gepagineerd; een huishouden heeft er een handvol.
         */
        get: operations["listLibraries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/libraries/{library_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blader door een bibliotheek.
         * @description Een bibliotheek van soort `shows` levert uitsluitend items met
         *     kind `show`. Seizoenen en afleveringen bereikt u via /items/{id}/children.
         */
        get: operations["listLibraryItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eén item met zijn versies en kijkstatus. */
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items/{item_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seizoenen van een serie, afleveringen van een seizoen.
         * @description Voor een film is het antwoord een lege lijst en geen fout.
         */
        get: operations["listItemChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Zoek over alle bibliotheken.
         * @description Resultaten zijn gewone itemobjecten. Er is geen apart resultaattype en
         *     geen groepering per soort; de client groepeert zelf en hoeft daarvoor
         *     geen tweede vorm te kennen.
         *
         *     Zonder kind levert een zoekopdracht items van soort movie, show en
         *     episode. Seizoenen blijven eruit: hun titel is "Season 3" en draagt
         *     niets van wat een gebruiker intypt, dus ze voegen alleen ruis toe aan
         *     korte zoektermen. Een seizoen is met kind=season wel op te vragen en
         *     staat verder in de kinderen van zijn serie.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hubs/{hub_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bouwstenen voor het homescherm.
         * @description De server levert bouwstenen en geen schermindeling; de client bouwt zijn
         *     eigen rijen. Een server zonder kijkstatus levert lege lijsten voor
         *     continue_watching en next_up, en geen fout.
         */
        get: operations["getHub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artwork/{artwork_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Een afbeelding, eventueel op maat.
         * @description Artwork is onveranderlijk: een andere afbeelding krijgt een ander id.
         *     In v1 levert de server uitsluitend afbeeldingen die naast de media op
         *     schijf staan; een 404 is daarom een normale toestand en geen storing.
         */
        get: operations["getArtwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subtitles/{subtitle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Een ondertitelbestand. */
        get: operations["getSubtitle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Direct play met HTTP-range.
         * @description Het hoofdpad en verreweg het meeste verkeer. Geen sessie, geen state,
         *     geen opruimwerk.
         *
         *     Eén bereik per aanvraag. Een Range-header met meerdere bereiken wordt
         *     beantwoord met het volledige bestand als 200; dat is de toegestane
         *     terugval en houdt een speler die het toch probeert aan de praat, waar
         *     een 416 hem zou breken.
         *
         *     De ETag verandert zodra de bytes van de versie veranderen. Hoe een
         *     server dat waarmaakt is geen protocol; dat hij het waarmaakt wel, want
         *     een client leunt erop bij If-Range na een onderbreking.
         */
        get: operations["getStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alles wat deze identiteit heeft aangeraakt.
         * @description Gesorteerd op updated_at aflopend. updated_since is wat de offline-laag
         *     gebruikt om na een periode zonder netwerk bij te trekken zonder de hele
         *     catalogus op te halen.
         */
        get: operations["listWatchState"];
        put?: never;
        /**
         * Meld wat er gebeurd is.
         * @description Een update is een gebeurtenis en geen waarde. De client stuurt niet "de
         *     positie is nu X" maar "dit is er gebeurd", en de server beslist wat dat
         *     voor de toestand betekent.
         *
         *     session_id is client-generated: de client maakt bij het starten van
         *     afspelen een UUID aan en houdt die aan tot hij stopt. Er zijn in v1
         *     bewust geen serverzijdige playbacksessies, dus er is ook geen endpoint
         *     dat een sessie-id uitdeelt.
         */
        post: operations["reportWatchState"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Ondoorzichtig voor de client. Er mag niets uit worden afgeleid, ook niet
         *     wanneer het op iets herkenbaars lijkt. Een pad is nooit een id.
         */
        Id: string;
        /**
         * Format: date-time
         * @description RFC 3339 in UTC, met Z-achtervoegsel.
         */
        Timestamp: string;
        /** @description Milliseconden. Nooit seconden, nooit een kommagetal. */
        DurationMs: number;
        ErrorEnvelope: {
            error: {
                /** @description Het contract. De client vertaalt codes en matcht nooit op message. */
                code: string;
                /** @description Voor logs, niet voor de UI. */
                message: string;
                /**
                 * @description Expliciet en geen afleiding uit de status, omdat een 503 soms wel
                 *     en een 409 soms niet te herhalen is.
                 */
                retryable: boolean;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        Info: {
            protocol: {
                /** @constant */
                major: 1;
                /**
                 * @description Wat de implementatie kan verstaan. Zegt niets over wat deze
                 *     server aanbiedt; daarvoor is capabilities leidend.
                 */
                feature_level: number;
                /** @enum {string} */
                profile: "minimal" | "full";
            };
            server: {
                id: components["schemas"]["Id"];
            };
            capabilities: components["schemas"]["Capabilities"];
            auth: {
                methods: ("password" | "pairing_code")[];
                /** @description True zolang er nog geen eigenaar is aangemaakt. */
                setup_required: boolean;
            };
        };
        /** @description Altijd leidend boven feature_level. */
        Capabilities: {
            browse: boolean;
            search: boolean;
            artwork: boolean;
            watch_state: boolean;
            /** @default false */
            playback_plan: boolean;
            /** @default false */
            transcode: boolean;
            /** @default false */
            downloads: boolean;
            /** @default false */
            live_tv: boolean;
            /** @default false */
            realtime: boolean;
            /** @default false */
            users: boolean;
        };
        ServerDetail: {
            id: components["schemas"]["Id"];
            name: string;
            version: string;
            started_at: components["schemas"]["Timestamp"];
        };
        SetupRequest: {
            setup_code: string;
            username: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            /** @description Roteert bij elk gebruik; het oude vervalt onmiddellijk. */
            refresh_token: string;
            /** @constant */
            token_type: "bearer";
            expires_in_ms: components["schemas"]["DurationMs"];
        };
        StreamTokenRequest: {
            version_id: components["schemas"]["Id"];
        };
        StreamToken: {
            stream_token: string;
            expires_at: components["schemas"]["Timestamp"];
        };
        /**
         * @description Er mag binnen v1 een soort bij komen. Een client die de soort niet kent
         *     toont de bibliotheek niet, en faalt niet.
         * @enum {string}
         */
        LibraryKind: "movies" | "shows";
        Library: {
            id: components["schemas"]["Id"];
            title: string;
            kind: components["schemas"]["LibraryKind"];
            item_count: number;
        };
        LibraryList: {
            items: components["schemas"]["Library"][];
        };
        /**
         * @description Er mag binnen v1 een soort bij komen. Een client die de soort niet kent
         *     toont het item niet, en faalt niet.
         * @enum {string}
         */
        ItemKind: "movie" | "show" | "season" | "episode";
        /** @description Ids van beschikbare afbeeldingen. Null wanneer er geen is. */
        Artwork: {
            poster_id?: components["schemas"]["Id"] | null;
            backdrop_id?: components["schemas"]["Id"] | null;
        };
        VideoStream: {
            id: components["schemas"]["Id"];
            index: number;
            codec: string;
            profile?: string | null;
            width?: number | null;
            height?: number | null;
            bit_depth?: number | null;
            frame_rate?: number | null;
        };
        AudioStream: {
            id: components["schemas"]["Id"];
            index: number;
            codec: string;
            channels?: number | null;
            /** @description ISO 639-2/B in drie letters, of null. */
            language?: string | null;
            title?: string | null;
            /** @default false */
            is_default: boolean;
        };
        /**
         * @description Twee soorten met hetzelfde veldenpakket. Extern heeft een url en geen
         *     index; ingebed heeft een index en geen url.
         */
        SubtitleStream: {
            id: components["schemas"]["Id"];
            /** @description Alleen bij ingebedde sporen. */
            index?: number | null;
            /**
             * @description Er mag binnen v1 een formaat bij komen. Een client die het formaat
             *     niet kent biedt het spoor niet aan, en faalt niet.
             * @enum {string}
             */
            format: "srt" | "ass" | "ssa" | "vtt" | "pgs" | "dvdsub";
            language?: string | null;
            title?: string | null;
            /** @default false */
            is_default: boolean;
            /** @description Expliciet, geen afleiding uit de titel. */
            is_forced: boolean;
            /** @description Expliciet, geen afleiding uit de titel. */
            is_hearing_impaired: boolean;
            is_external: boolean;
            /** @description Alleen bij externe sporen. */
            url?: string | null;
        };
        Version: {
            id: components["schemas"]["Id"];
            container: string;
            duration_ms: components["schemas"]["DurationMs"];
            /**
             * @description Een versie mag uit meerdere bestanden bestaan; dat is geldig in het
             *     domeinmodel. Direct play accepteert in v1 uitsluitend 1.
             */
            file_count: number;
            /** @description Bijvoorbeeld "Director's Cut". Onderscheidt twee snedes van dezelfde titel. */
            edition?: string | null;
            video_streams?: components["schemas"]["VideoStream"][];
            audio_streams?: components["schemas"]["AudioStream"][];
            subtitle_streams?: components["schemas"]["SubtitleStream"][];
        };
        /**
         * @description De leeskant van kijkstatus. Reist mee in elk itemantwoord, zodat een
         *     detailscherm geen tweede aanvraag nodig heeft.
         */
        UserState: {
            position_ms: components["schemas"]["DurationMs"];
            watched: boolean;
            play_count: number;
            updated_at: components["schemas"]["Timestamp"];
        };
        Item: {
            id: components["schemas"]["Id"];
            kind: components["schemas"]["ItemKind"];
            title: string;
            sort_title?: string | null;
            year?: number | null;
            added_at: components["schemas"]["Timestamp"];
            duration_ms?: components["schemas"]["DurationMs"] | null;
            parent_id?: components["schemas"]["Id"] | null;
            /** @description Seizoen- of afleveringsnummer. */
            index?: number | null;
            child_count?: number | null;
            /** @description Backend-neutrale naam; het interne model van de client heet anders. */
            episode_count?: number | null;
            watched_episode_count?: number | null;
            artwork?: components["schemas"]["Artwork"];
            versions?: components["schemas"]["Version"][];
            user_state?: components["schemas"]["UserState"] | null;
        };
        Page: {
            /** @description Null op de laatste pagina. */
            next_cursor: string | null;
            /**
             * @description Expliciet een schatting, zodat een UI een scrollbar kan tekenen
             *     zonder dat de server per pagina telt. Nooit als exact aantal tonen.
             */
            total_estimate?: number | null;
        };
        ItemPage: components["schemas"]["Page"] & {
            items: components["schemas"]["Item"][];
        };
        /**
         * @description Een expliciete handeling wint van elke passieve update die ervoor ligt.
         *     Dat onderscheid is de reden dat een update een gebeurtenis is.
         * @enum {string}
         */
        ExplicitAction: "none" | "mark_watched" | "mark_unwatched" | "restart";
        WatchStateEvent: {
            item_id: components["schemas"]["Id"];
            /**
             * @description Client-generated. De client maakt bij het starten van afspelen een
             *     UUID aan en houdt die aan tot hij stopt.
             */
            session_id: string;
            position_ms: components["schemas"]["DurationMs"];
            duration_ms?: components["schemas"]["DurationMs"] | null;
            /**
             * @description Het moment volgens de client. De server bewaart daarnaast zijn eigen
             *     ontvangstmoment, want een toestel met een scheve klok mag de
             *     volgorde niet bepalen.
             */
            occurred_at: components["schemas"]["Timestamp"];
            /** @default false */
            completed: boolean;
            explicit_action: components["schemas"]["ExplicitAction"];
        };
        WatchStateEntry: {
            item_id: components["schemas"]["Id"];
            state: components["schemas"]["UserState"];
        };
        WatchStatePage: components["schemas"]["Page"] & {
            items: components["schemas"]["WatchStateEntry"][];
        };
    };
    responses: {
        /** @description Fout met een stabiele machineleesbare code. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        LibraryId: components["schemas"]["Id"];
        ItemId: components["schemas"]["Id"];
        /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
        Limit: number;
        /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
        Cursor: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Sterke validator. Verandert zodra de bytes veranderen. Ondoorzichtig:
         *     een client ontleedt hem niet en leidt er niets uit af.
         */
        ETag: string;
        AcceptRanges: "bytes";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serverinformatie. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"];
                };
            };
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Eigenaar aangemaakt, tokenpaar uitgegeven. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Tokenpaar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /**
             * @description auth.invalid_credentials. Een onbekende gebruiker en een verkeerd
             *     wachtwoord geven hetzelfde antwoord, zodat het bestaan van een
             *     account niet lekt.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Nieuw tokenpaar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    issueStreamToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamTokenRequest"];
            };
        };
        responses: {
            /** @description Streamtoken. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamToken"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Naam, versie en starttijd. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerDetail"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listLibraries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bibliotheken. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryList"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listLibraryItems: {
        parameters: {
            query?: {
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Een voorafgaand minteken keert de volgorde om. */
                sort?: "title" | "added_at" | "year" | "-title" | "-added_at" | "-year";
            };
            header?: never;
            path: {
                library_id: components["parameters"]["LibraryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Het item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listItemChildren: {
        parameters: {
            query?: {
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                item_id: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                kind?: components["schemas"]["ItemKind"];
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina items. Geen treffers is een lege lijst, geen fout. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getHub: {
        parameters: {
            query?: {
                library_id?: components["schemas"]["Id"];
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                hub_id: "recently_added" | "continue_watching" | "next_up";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getArtwork: {
        parameters: {
            query?: {
                /** @description Zonder deze parameter krijgt u het origineel. */
                width?: number;
            };
            header?: never;
            path: {
                artwork_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description De afbeelding. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    /** @description Lang, want artwork is onveranderlijk. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            /** @description Niet gewijzigd. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getSubtitle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subtitle_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Het ondertitelbestand. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-subrip": string;
                    "text/x-ssa": string;
                    "text/vtt": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getStream: {
        parameters: {
            query?: never;
            header?: {
                /** @example bytes=0-1048575 */
                Range?: string;
                /** @description De eerder ontvangen ETag. */
                "If-Range"?: string;
            };
            path: {
                version_id: components["schemas"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Het hele bestand. Ook het antwoord op meerdere bereiken. */
            200: {
                headers: {
                    "Accept-Ranges": components["headers"]["AcceptRanges"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Het gevraagde bereik. */
            206: {
                headers: {
                    "Accept-Ranges": components["headers"]["AcceptRanges"];
                    ETag: components["headers"]["ETag"];
                    /** @example bytes 0-1048575/5368709120 */
                    "Content-Range"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            /**
             * @description library.version_multifile. De versie bestaat uit meer dan een
             *     bestand. Dat is een geldige versie in het domeinmodel; v1 begrenst
             *     alleen de levering.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            415: components["responses"]["Error"];
            /** @description playback.range_not_satisfiable. */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    listWatchState: {
        parameters: {
            query?: {
                updated_since?: string;
                /** @description Een hogere waarde wordt naar het maximum teruggebracht en is geen fout. */
                limit?: components["parameters"]["Limit"];
                /** @description Ondoorzichtig. Hoort bij een sortering; bij een andere sortering ongeldig. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Een pagina kijkstatusregels. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchStatePage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    reportWatchState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchStateEvent"];
            };
        };
        responses: {
            /** @description De nieuwe toestand van het item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserState"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
