import 'dart:io';

import 'package:pleya/automation/automation_ids.dart';

/// Regenerates `pleya_verify/automation_ids.yaml` from the single source of
/// truth, `AutomationIds.catalog()`. Run after adding/changing an id:
///
/// ```
/// dart run tool/generate_automation_ids_yaml.dart
/// ```
///
/// `test/architecture/automation_ids_yaml_test.dart` fails if the committed
/// yaml and the catalog it should mirror ever drift apart.
///
/// **This program must never reach `package:flutter`.** `dart run` compiles on
/// the standalone Dart VM, whose FFI use-site transformer cannot compile the
/// Flutter framework at all: a script whose only line is
/// `import 'package:flutter/material.dart';` crashes it with
/// `type 'InvalidType' is not a subtype of type 'FunctionType' in type cast`
/// from `_FfiUseSiteTransformer._verifyAndReplaceNativeCallable`. That is a
/// toolchain problem on Flutter 3.44.0 / Dart 3.12.0 and nothing here fixes
/// it, so the import path stays clear of Flutter instead: [AutomationIds]
/// names a tab through `lib/navigation/navigation_tab_id.dart`, not through
/// the widget file that re-exports it.
/// `test/architecture/automation_ids_generator_test.dart` walks this path and
/// fails the moment a Flutter import lands on it, which is a better place to
/// find out than a compiler crash with no mention of the import that caused
/// it. Never hand-edit the yaml to get around a broken generator: that gives
/// the catalogue a second source of truth, which is the one thing this file
/// exists to prevent.
void main() {
  final buffer = StringBuffer()
    ..writeln('# Generated by tool/generate_automation_ids_yaml.dart — do not hand-edit.')
    ..writeln("# Mirrors lib/automation/automation_ids.dart's AutomationIds.catalog(),")
    ..writeln('# served live at GET /v1/automation_ids.')
    ..writeln('#')
    ..writeln('# `instanceable: true` marks a base id a scenario may address as')
    ..writeln('# `id[instance]` (e.g. `library.grid.item[3]`) — see the Pleya Verify plan\'s')
    ..writeln('# Fase 5 instance-ID semantics.')
    ..writeln('ids:');
  for (final entry in AutomationIds.catalog()) {
    buffer.writeln('  - id: ${entry['id']}');
    buffer.writeln('    role: ${entry['role']}');
    buffer.writeln('    instanceable: ${entry['instanceable']}');
  }
  File('pleya_verify/automation_ids.yaml').writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote pleya_verify/automation_ids.yaml (${AutomationIds.catalog().length} ids).');
}
