import 'dart:io';

import 'package:pleya/automation/automation_ids.dart';

/// Regenerates `pleya_verify/automation_ids.yaml` from the single source of
/// truth, `AutomationIds.catalog()`. Run after adding/changing an id:
///
/// ```
/// dart run tool/generate_automation_ids_yaml.dart
/// ```
///
/// `test/architecture/automation_ids_yaml_test.dart` fails if the committed
/// yaml and the catalog it should mirror ever drift apart.
void main() {
  final buffer = StringBuffer()
    ..writeln('# Generated by tool/generate_automation_ids_yaml.dart — do not hand-edit.')
    ..writeln("# Mirrors lib/automation/automation_ids.dart's AutomationIds.catalog(),")
    ..writeln('# served live at GET /v1/automation_ids.')
    ..writeln('#')
    ..writeln('# `instanceable: true` marks a base id a scenario may address as')
    ..writeln('# `id[instance]` (e.g. `library.grid.item[3]`) — see the Pleya Verify plan\'s')
    ..writeln('# Fase 5 instance-ID semantics.')
    ..writeln('ids:');
  for (final entry in AutomationIds.catalog()) {
    buffer.writeln('  - id: ${entry['id']}');
    buffer.writeln('    role: ${entry['role']}');
    buffer.writeln('    instanceable: ${entry['instanceable']}');
  }
  File('pleya_verify/automation_ids.yaml').writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote pleya_verify/automation_ids.yaml (${AutomationIds.catalog().length} ids).');
}
