import 'package:flutter/material.dart';

/// The Pleya "P" mark, as generated by `scripts/gen_brand_assets.py` into
/// `assets/branding/pleya_logo.png`.
///
/// The source is a transparent RGBA PNG with no fill and no baked-in
/// background — the P is meant to sit directly on whatever surface a callsite
/// already has. Do not wrap this in a `ClipRRect`, `ClipOval`, `DecoratedBox`
/// with a `color`, or any other rectangular/circular clip or fill: those were
/// only ever needed for the old opaque asset, which had a black square baked
/// into its own pixels, and they read as a visible tile or halo behind a
/// transparent mark.
class PleyaLogo extends StatelessWidget {
  const PleyaLogo({super.key, required this.size});

  final double size;

  @override
  Widget build(BuildContext context) {
    return Image.asset(
      'assets/branding/pleya_logo.png',
      width: size,
      height: size,
      fit: BoxFit.contain,
      filterQuality: FilterQuality.high,
    );
  }
}
